### ISSUE TITLE
Implementierungsstand der Middleware

### ISSUE THREAD

**Issue by Zarok123** [hu-semesterprojekt-genombrowser/Alazen#20]
Bitte das Dokument dahingehend anpassen und den aktuellen Stand ebenfalls aktualisieren
**Deadline:** 22.01.2016

Middleware:
* Unit-Tests der Spezifikation implementieren, durchführen und Ergebnisse ins Dokument einbinden.
* Neue Zeitmessung, diesmal mit den Testdaten, die in der Datenbank bereitgestellt sind (ca. 1Mio. Datensätze)
* Stresstest durchführen.

**Comment by tobiasloeffler** [comment]
Wo ist denn die Datenbank mit den Mio. Daten? Auf der vm4 sind immer noch nur 22 Mutationen in der DB.

**Comment by BenSchumacher-HU** [comment]
Die Daten müssen noch von der Integration geparsed werden und stehen dann in der DB

**Comment by Zarok123** [comment]
Meine Bahn trödelt.... die hätte vor 6min in Adlerhof sein müssen, bin
jetzt aber erst Schöneweide...

**Comment by Zarok123** [comment]
Bitte den aktuellen Stand ebenfalls aktualisieren.

**Comment by BenSchumacher-HU** [comment]
Die Daten sind jetzt in der DB drin

**Comment by BenSchumacher-HU** [comment]
Inhaltlich gut, aber die Tabelle auf der zweiten Seite ist noch kaputt. Fixed du die noch?

**Comment by Martin-Bauer** [comment]
Ich glaube das gehört zur Integration oder? :)

**Comment by BenSchumacher-HU** [comment]
Alles super :+1:
