### ISSUE TITLE
Implementierungsstand der Integration

### ISSUE THREAD

**Issue by Zarok123** [hu-semesterprojekt-genombrowser/Alazen#21]
Bitte das Dokument dahingehend anpassen und den aktuellen Stand ebenfalls aktualisieren
**Deadline:** 22.01.2016

Integration:
* Tests durchführen und Ergebnisse ins Dokument einbinden

**Comment by Zarok123** [comment]
Bitte den aktuellen Stand ebenfalls aktualisieren.

**Comment by Zarok123** [comment]
Bitte noch Testergebnise in die Tex-Datei integrieren

**Comment by Zarok123** [comment]
Bitte bis heute Abend, 20 Uhr.

**Comment by MasterOfDesaster** [comment]
Was für Testergebnisse sollen denn noch wie integriert werden? Wir haben Testdateien für die lokalen Parser, die die Datei so parsen, wie sie geparst werden sollen, wir werden die natürlich noch mit hochladen, aber was soll ich dafür schreiben? Reicht es zu erwähnen, dass die existieren und wie gewünscht laufen?

**Comment by Zarok123** [comment]
Marius hatte noch ganze Dateien mit Testdaten gepushed - sind die soweit in das PDF integriert?

**Comment by MasterOfDesaster** [comment]
Also eine Tabelle mit den Testergebnissen von den GParser-Testfiles ist drin.
Bei den LParsern kann ich höchstens erwähnen, dass wir für beide jeweils eine Testklasse hat, die exemplarisch einen Auszug aus den jeweiligen Files parsed und das auch erfolgreich. Sonst wüsste ich nichts, was da noch Testmäßig reinkönnte.

**Comment by Zarok123** [comment]
Das wäre super! =)

**Comment by MasterOfDesaster** [comment]
So, hab's erwähnt ^^

**Comment by BenSchumacher-HU** [comment]
Inhaltlich gut, aber die Tabelle auf der zweiten Seite ist noch kaputt. Fixed du die noch?

**Comment by Zarok123** [comment]
Fix der Tabelle erledigt. Nur noch nicht online.

**Comment by Zarok123** [comment]
Ist online.
Somit ist die Integration fertig. Danke.

**Comment by BenSchumacher-HU** [comment]
Eigentlich war das an Gabriel gerichtet
