### ISSUE TITLE
Projektdokumentation der Integration

### ISSUE THREAD

**Issue by Zarok123** [hu-semesterprojekt-genombrowser/Alazen#23]
Projektdokumentation.tex
Deadline: **04.02.2016**
Branch: documentation/integration

Bitte foldenge Punkte auf den IST-Stand zur Abgabe ändern. Diesmal bitte wie ihr es macht.

 * ~~Ablauf der Integration:~~
      * ~~Bitte um Steuerprogramm erweitern~~
      *  ~~Zudem den Download anpassen~~
      * ~~Ebenfalls Auswahl beschreiben, ob Daten neu integriert werden sollen, oder ob die alten Daten erhalten bleiben sollen~~
      * ~~Generell Änderungen im Ablauf~~

* ~~Eigener Abschnitt zu Steuerprogamm, was es macht usw.~~  (In Ablauf der Integration abgedeckt)

* ~~Mengengerüst auf den IST-Stand aktualisieren~~

* ~~Eventuelle Änderungen bei Inputfileformaten oder EBNF darstellen~~

* ~~Sequenzdiagramm des Steuerprogramms um Steuerprogramm erweitern und somit auch die Beschreibung aktualisieren~~

* ~~Datenbankentwurf:~~
      * ~~Aufnehmen, wie Start und Ende einer Mutation definiert sind~~

* Genauere Beschreibung der Parser und deren Struktur (z.B. Singleton) usw.

* ~~Klassendiagramm um neue Klassen erweitern (Interfaces, Quell bzw. Downloadklassen, Parser etc.) und die Methoden aufnehmen (siehe Klassendiagramm der Middleware)~~

* ~~Abschnitt über Abweichungen der Implementierung bzgl der Projektspezifikation~~

* ~~Unit-Tests anpassen (die gestrichenen raus, neue rein) und Testergebnisse reinkopieren~~

* ~~Anhang gegebenenfalls anpassen (kürzen bzw. erweitern)~~

* ~~Schnittstelle Benutzer:~~
      * ~~Genau den Einbindungsprozess beschreiben - was muss man genau machen, damit eine weitere Quelle integriert wird~~

**Comment by MasterOfDesaster** [comment]
Was genau ist mit dem Punkt zur Schnittstelle Middleware gemeint? Wir wissen doch nicht, was für Abfragen die Middleware an uns stellt, wir stellen nur die Daten bereit ^^

Und zum Mengengerüst können wir eine Angabe für dbSNP machen, wir wissen auch, dass ein Datensatz ca. 0,1kB Speicher verbraucht, jedoch wissen wir nicht, wie viele Mutationen pro Chromosom existieren, da das variiert, besonders durch die Anzahl der Personen, die diese Mutation aufweisen. z.B. das Chromosom 21 hatte bereits mehr Mutationen als die gesamte dbSNP Datenbank, da können wir leider nichts approximieren, es seidenn, wir nehmen die Größe vom Chromosom 21 und rechnen die dann per Anzahl der Chromosome hoch, das ginge, aber etwas genaueres wissen wir leider auch nicht.

**Comment by Zarok123** [comment]
Welche Anfragen gestellt werden dürfen, Beispielanfragen hierfür usw. - Im Zweifel einmal die Middleware fragen.

Bzgl. des Mengengerüstes: 
Wie groß ist die Datenbank ca. - im Zweifel bitte für 1kGenomes hochrechnen (worst case, mittelwert, best case) - wieviele Datensätze ca. (GB, etc. pp.) muss nicht für jedes Chromosom einzeln sein, sondern für alle zusammen.
Und für die dbSNP einfach das, was ihr habt, reinschreiben - die is ja schon fertig geparsed usw.

**Comment by MasterOfDesaster** [comment]
So, ich hoffe ich hab da jetzt alles drin, was aktualisiert werden musste ^^
Falls doch noch was fehlt, Bescheid sagen.

**Comment by Zarok123** [comment]
Super, danke! =) 
Werde ich mir dann morgen durchlesen und falls noch was fehlt, werde ich bescheid geben.

**Comment by BenSchumacher-HU** [comment]
@MasterOfDesaster  Ich habe den Root Kommentar geupdatet. Bitte ergänze, was noch fehlt

**Comment by BenSchumacher-HU** [comment]
Merged
