### ISSUE TITLE
Projektdokumentation der Middleware

### ISSUE THREAD

**Issue by Zarok123** [hu-semesterprojekt-genombrowser/Alazen#24]
Projektdokumentation.tex
Deadline: **04.02.2016**
Branch: documentation/middleware

Bitte foldenge Punkte auf den IST-Stand zur Abgabe ändern. Diesmal bitte wie ihr es macht.

* ~~Beschreibung der Middleware:~~
   * ~~Diagramme, sowie deren Beschreibung auf aktuellen Stand anpassen~~
   * ~~Ablauf bzw. Beschreibung anpassen:~~
        * ~~GenTranslator und Index sind unabhängig voneinander~~

* ~~IndexController:~~
   * ~~Umsetzung als Servlet einbringen~~
   * ~~Eventuelle Änderungen am IndexController bitte einpflegen~~
   * ~~Eventuelle Änderungen im Pseudocode berücksichtigen~~

* ~~Index~~
   * ~~Umsetzung der Parallelisierung hinzufügen und erklären (falls hier falsche Stelle, dann woanders)~~
   * ~~Eventuelle Änderungen am Index bitte einpflegen~~
   * ~~Eventuelle Änderungen im Pseudocode berücksichtigen~~

* ~~GeneTranslator:~~
   * ~~RefSeq bitte einbringen -> hierzu gehört Umsetzung etc.pp.~~
   * ~~Eventuelle Änderungen am GeneTranslator bitte einpflegen~~
   * ~~Eventuelle Änderungen im Pseudocode berücksichtigen~~

* QuerryReceiver
   * Beschreiben, wie die Query weitergeleitet werden, ob an GeneTranslator oder Index 
   * ~~Eventuelle Änderungen am Index bitte einpflegen~~
   * ~~Eventuelle Änderungen im Pseudocode berücksichtigen~~

* ~~Abschnitt über alle Änderungen zur Projektspezifikation~~

* Unit-Tests
   * ~~Unitests aktualisieren, nicht umgesetzte entfernen, neue hinzufügen und Ergebnisse einbinden~~ (Bitte nochmal prüfen)

* Stresstest:
     * ~~Aktualisieren des Testverfahrens~~ + Ergebnisse einbinden

* ~~Anhang gegebenenfalls anpassen und erweitern~~

* Schnittstelle Integration - Middleware:
      * Genaue SQL-Anfragen hinzufügen, die ausgeführt werden

* Schnittstelle Frontend - Middleware
    * Das endgültige JSON-Format beschreiben und alle Beschreibungen anpassen (siehe c6ef376bb9ae839a8b4bb5d789a2e5e46e35e8d1)
    * Änderungen zur Projektspezifikation beschreiben und begründen

**Comment by BenSchumacher-HU** [comment]
@Martin-Bauer Ich habe den Root Kommentar geupdatet und durchgestrichen, was meiner Meinung nach fertig ist. Guck mal bitte, ob ich was vergessen habe.<br>
Genelle verstehe ich nicht, warum du deine Änderungen in `Middleware_Form_Spez.tex` eingefügt hast? Eigentlich war dafür `Middleware.tex` vorgesehen. Es dürfte sehr schwierig werden, die Änderungen zu übernehmen. In `Middleware.tex` gibt es einige Änderungen, die neuer sind

**Comment by Martin-Bauer** [comment]
Gut zu wissen, das war so aus der Erklärung nicht ganz ersichtlich, wo die Änderungen zu tätigen sind - ich schmeiß die Änderungen in Middleware.tex rein

**Comment by Martin-Bauer** [comment]
Jetzt müssten die Änderungen drin sein

**Comment by BenSchumacher-HU** [comment]
@Martin-Bauer Super soweit. Sind alle Änderungen für den QuerryReceiver drin? Hat sich bei den Unittests noch was geändert? Muss am Anhang noch was gemacht werden?

**Comment by Martin-Bauer** [comment]
Hi,
Soweit dürften alle Änderungen drin sein, wenn ich nichts vergessen abe. 
Von meiner Gruppe kam auch kein Feedback, deshalb geh ich mal davon aus, 
dass das passen dürfte.
Anhang ist auch angepasst

Grüße,
Martin
