### ISSUE TITLE
Projektdokumentation des Frontends

### ISSUE THREAD

**Issue by Zarok123** [hu-semesterprojekt-genombrowser/Alazen#25]
Projektdokumentation.tex
Deadline: **04.02.2016**
Branch: documentation/frontend

Bitte folgende Punkte auf den IST-Stand zur Abgabe ändern. Diesmal bitte wie ihr es macht.

* ~~Use-Cases:~~
   * ~~Bitte anpassen, hier auch die Filter mit einbringen~~

* ~~Mock-Ups:~~
   * ~~Abschnitt bitte anpassen. Hierbei nicht mehr Mock-Ups, sondern das fertige Produkt beschreiben und was diese kann. Auch bitte die Umsetzung beschreiben.Genaue Zoom-Stufen-Anzahl angeben etc. pp.~~ 

* Technologie und Klassenstruktur
   * ~~Bitte Absatz an den finalen Stand anpassen. Ebenso das Klassendiagramm aktualisieren.~~
   * Wichtige Klassen bitte genauer in ihrer Umsetzung beschreiben.

* ~~Sequenzdiagramm~~
   * ~~Eventuell das Sequenzdiagramm erweitern oder zusammenstreichen - je nach Änderungen beim finalen Stand. Bitte ebenso die Beschreibung anpassen.~~

* ~~Abschnitt über alle Änderungen bzgl der Projektspezifikation~~
   * ~~Welche Features haben es nicht geschafft, was wurde verändert etc.~~

* ~~Unit-Tests:~~
   * ~~Durchführung der Unit-Tests beschreiben~~
   * ~~Nicht implementierte Unit-Tests streichen, neue hinzufügen~~
   * ~~Testergebnisse hinzufügen~~

* ~~Anhang:~~
    * ~~Eventuell Werte anpassen~~

**Comment by kasperkopf** [comment]
Es fehlen noch die Bilder der aktuellen GUI, da wird noch Sachen anpassen mussten.
Außerdem fehlt noch die Änderung bzgl. der Porjektspezifikation, da wir noch am umsetzten sind was damals nicht geklappt hat.
Außerdem sind die Unit-Test nicht aktuell.

**Comment by BenSchumacher-HU** [comment]
Updatet Root Kommentar

**Comment by BenSchumacher-HU** [comment]
Mit 0491bfc809be68d5b8f51637d59771d8fb49a687 abegschlossen
