### ISSUE TITLE
Projektdokumentation

### ISSUE THREAD

**Issue by Zarok123** [hu-semesterprojekt-genombrowser/Alazen#32]
* ~~Die Abweichungen des SOLL- vom IST-Zustand sind über verschiedene
   Kapitel verteilt (Kapitel 3.3, Kapitel 11), unvollständig und im
   Wesentlichen in Form einer Stichpunktliste beschrieben. Hier wünschen wir
   uns (a) eine Vereinheitlichung (Zusammenführung oder einheitliche
   Trennung nach Teilprojekt) der Kapitel, die sich mit SOLL und IST
   beschäftigen, (b) eine Vervollständigung, wobei insbesondere die zentralen
   und von außen erkennbaren Einschränkungen (z.B. die Beschränkung auf nur
   ein Chromosom) erwähnt und vor allem auch begründet werden und (c) eine
   strukturiertere Übersicht (z.B. unterteilt nach Teilprojekt und in die
   Kategorien "gestrichenes Feature" und "nachträglich hinzugefügtes
   Feature"). Nett wäre auch die Vergabe von IDs, z.B. "Feature 1 -
   Integration von Metadaten", so dass man sich später darauf beziehen könnte.~~
* ~~Es fehlt ein kleines Fazit mit Ausblick. Hier reichen ein paar
   Absätze, z.B. dazu (a) was Alazen alles (gut) kann, (b) welche Lehren aus
   dem Projekt gezogen wurde, also was gut funktioniert hat und was man im
   Nachhinein anders gemacht hätte (hier könnte man z.B. ansprechen, dass das
   Datenvolumen besser verwaltbar gewesen wäre, wenn man die Daten bereits in
   der Datenbank zusammengefasst hätte) und (c) um welche Features man Alazen
   sinnvollerweise erweitern könnte (wenn man mehr Zeit hätte).~~
* ~~Es fehlen noch ein paar konkrete Informationen dazu, wo der Code
   liegt, woher die Daten kommen, wie man Alazen installiert, initialisiert,
   nutzt. Also so eine Art "Erste Schritte", wobei hier durchaus Bezug auf
   bestehende Ressourcen (GitHub Wiki, Dokument zum Ablauf der Integration)
   genommen werden kann.~~

**Comment by Zarok123** [comment]
Lediglich die Abweichung Soll/Ist fehlt noch. Außerdem eine erneute Rechtschreibkontrolle.

**Comment by Zarok123** [comment]
Alles angepasst, was angemerkt wurde. Nur eine Rechtschreibkontrolle, sowie die Kapitelangabenkorrektur und einige Bildnummernanpassungen stehen noch aus.

**Comment by BenSchumacher-HU** [comment]
Fixed Rechtschreibung mit 7d30460cbee0915b23446bd6cfda1fb58e050d67
Fixed Nummerierung mit c85b40d891b743deaa4fe89a099abdc8d60b6ed5
Somit ist alles fertig, oder?

**Comment by Zarok123** [comment]
Jup :) fertig dann, danke :)
