### ISSUE TITLE
Ablauf der Integration überarbeiten

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen#33]
Ein paar Sachen müssen noch überarbeitet werden:

- Fügt noch paar Screenshots von dem Inhalt der DB ein
- Fügt zu den Screenshots bitte die SQL Statements hinzu, mit denen diese erzeugt wurden
- Bei der Installation müssen noch ein paar Sachen überarbeitet werden( @KacperSiedlecki weiß, was geändert werden muss)

@MasterOfDesaster  Wer kümmert sich um die Screenshots?

Die Änderungen müssen bis Sonntag 15 Uhr gepusht sein.

@Zarok123 Kannst du bitte den Tex-Quellcode hoch pushen?

**Comment by KacperSiedlecki** [comment]
Die Mail von Marc wo stand was falsch ist habe Ich schon vor einiger Zeit an Gabriel und Marius weitergeleitet. 
Btw. Ist irgendwas vor wegen Kuchen und Caffe am Dienstang bekannt? Wurde mehrfach angesprochen, aber nie konkret :D

**Comment by Zarok123** [comment]
Die Änderungen in dem Abschnitt über die Installation müssen dann ebenfalls in die Projektdokumentation eingebunden werden. Nur als Hinweis.

**Comment by Zarok123** [comment]
2 der SELECT-Statements hinzugefügt und in dem Zuge die Featurere-Listen-Beschreibung für 1k Genomes angepasst (Chromosom 15 und 21.)

**Comment by BenSchumacher-HU** [comment]
Abgeschlossen und abgeschickt
