### ISSUE TITLE
Prezifikation der Middleware korrigieren

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen#6]
Folgendes muss korrigiert werden:

* ~~In 4.2 heißt es:~~
  *  ~~"die komplett innerhalb des angegebenen Intervalls liegen."~~
* ~~und in 4.3:~~<br>
  *  ~~"der Index gibt alle Intervalle zurück, die sich in irgendeinem Punkt mit dem gesuchten Intervall überschneiden."~~<br>
* ~~Soll das so?~~
* ~~Seite 25, GeneTranslator: Es ist *immer noch* nicht klar, wer RefEq runterlädt, parst, und aufbereitet. Hier liest es sich so, als ob das die Integrationsgruppe macht - da wird aber nichts dergleichen spezifiziert. Es muss festgelegt werden, wer sich um dieses Thema kümmert~~
* ~~Seite 26: search() gibt immer nur eine Ergebnis zurück. Das soll wohl nicht so sein?~~
* ~~4.6.1 braucht eine Überarbeitung. Die Testes sollen nicht nur testen, ob der QueryReceiver funktioniert, also ob der das JSON erkennt und parsen kann, sondern auch ob die gesamte Middleware funktioniert. D.h. ob die Middleware auf Grundlage einer Testdatenbank Querys beantworten kann. Legt dazu eine Testdatenbank fest (muss nicht groß sein, ~ 15 Einträge) und führt darauf Querys aus. Dann braucht ihr auch in den Antworten keine Platzhalter mehr zu verwenden~~
* ~~4.6.2: Woher nimmt der IndexController die Datenbank auf deren Grundlage er die Anfragen erstellt? Kannst du bitte noch Tests mit mehr als einem Ergebnis ergänzen~~
* ~~4.7: Es wird bei den Testfällen 4-9 nicht klar, was die Voraussetzungen sind. Macht das am Besten nach dem Muster:~~<br>
```
Testvorbereitung: addGene(Testgen, 350, 500)
Testfall 4 - tranlateToIntervall - erfolgreiche Suche
Eingabe: Testgen
Ausgabe: [(350, 500)]

Testfall 5 - tranlateToIntervall - erfolglose Suche
Eingabe: Testgen2
Ausgabe: []
...
``` 
* ~~Bitte fügt für 4.7. noch Tests für nur teilweise Überschneidung hinzu.~~
```
Testvorbereitung: addGene (TestGen, 350,500)
Tests:
search( 300,600) -> Ergebnis "TestGene"
search( 380,600) -> Ergebnis "TestGene" (oder leer, je nach Antwort auf die erste Frage oben)
search( 100, 200) -> Ergebnis leer

````

* ~~4.7.1 ist ein wenig merkwürdig. Es wirkt eher wie eine Erklärung, wie Bäume funktionieren, als ein Test. Zudem wird ja eine externe Bibliothek verwendet, da sind Tests ja überflüssig. (Wobei man auch externe Bibliotheken testen kann, wenn man will). Also entweder überarbeitet ihr den Abschnitt oder nimmt ihn raus~~

**Comment by tobiasloeffler** [comment]
Den Unterschied zwischen 4.2 und 4.3 werde ich korrigieren und für die 4.6.2 noch Testfälle ergänzen (und dann natürlich auch das Testprogramm anpassen).

Die search()-Funktion gibt nicht nur ein Ergebnis zurück, die Funktion arbeitet rekursiv. Anscheinend wird das aus dem Pseudocode nicht so ganz klar.

Zur 4.6.2: Ich habe geschrieben "aus der aktuellen Datenbank". Reicht das nicht? Sollen wir da die kleine Testdatenbank in Tabellenform mit angeben, oder sollen wir das nur nochmal ein bisschen klarer formulieren?

**Comment by BenSchumacher-HU** [comment]
Wenn du angibst, was der Inhalt der Datenbank ist, ist das vollkommen in Ordnung. Es muss nur für außen stehende erkennbar sein, was der Inhalt der DB ist.

**Comment by BenSchumacher-HU** [comment]
* Warum gibt `search()` einen Boolean zurück? Wenn einfach nur die `answer_list` zurückgegeben wird, macht das den Code einfacher und man verliert dabei keine Information. Warum ist es für die letzte if abfrage notwendig, das `b2=true` ist?
* Zu 4.6.1: Viel besser, die Testdankenbank ist super. Die Formatierung der Testfälle ist noch verrucht. Erik wird noch Änderungen am JSON vornehmen, ihr müsst also die Test noch ein wenig überarbeiten, wenn er das abgeschlossen hat. Fügt noch bitte einen Verweis auf den Anhang hinzu

**Comment by tobiasloeffler** [comment]
Es gibt noch eine Wrapper-Funktion für search(), die eine neue Liste erstellt und danach die richtige Suchfunktion am Wurzelknoten aufruft. Diese Wrapper-Funktion gibt dann auch wie gewünscht die answer_list zurück.
Wenn b2=true nicht gefordert werden würde, dann würde man nie in den rechten Subtree gucken, sobald man im linken ein Ergebnis findet.

**Comment by BenSchumacher-HU** [comment]
Ich verstehe die letzte if Abfrage nicht.:confused: Warum reicht
`max. endpoint in left subtree $<$ start of the searched interval}
+{b3 = search(input, current.right, answer\_list)\;}`
nicht aus? Warum kann man statt den OR der b's nicht gucken ob answer_list leer ist?

**Comment by tobiasloeffler** [comment]
In der zweiten if-Abfrage hast du: max. endpoint in left subtree >= start of searched interval. Wenn man in der letzten if-Abfrage jetzt nur noch prüfen würde, ob max. endpoint in left subtree < start of searched interval, dann könntest du nie in beiden Subtrees suchen (weil sich die Bedingungen gegenseitig ausschließen). Die Bedingung für den linken Subtree schließt aber nicht aus, dass es im rechten auch Ergebnisse gibt.
Die Überprüfung ob answer_list leer ist funktioniert nur, wenn sie vorher auch leer war. Falls du aber z.B. im linken Subtree der Wurzel Ergebnisse findest und an irgendeiner Stelle im rechten Subtree nicht mehr, dann hast du trotzdem schon die Ergebnisse aus dem linken Subtree in answer_list gespeichert.

**Comment by BenSchumacher-HU** [comment]
Wann sollte ich nicht in beiden Subbäumen suchen wollen?

**Comment by tobiasloeffler** [comment]
Man sucht nicht im linken Teilbaum, falls es ihn nicht gibt, oder falls der max. endpoint < start of searched interval. In diesen Fällen kann im linken Teilbaum definitiv kein Ergebnis liegen.

Im rechten Teilbaum sucht man nur dann nicht wenn man im linken Teilbaum gesucht hat, aber dort kein Ergebnis gefunden hat. Ich versuche mal zu erklären warum es kein Ergebnis im rechten Teilbaum geben kann:

Voraussetzung:
max. endpoint in left subtree >= start of searched interval

Du guckst dir das Intervall i_Max aus dem linken Teilbaum an das den max. Endpunkt im linken Teilbaum hat:

i_Max:
x [------------------------------------------------] y <-- max. endpoint

Weil wir im linken Teilbaum suchen wissen wir automatisch, dass der Startpunkt unseres gesuchten Intervalls (i_Q) <= dem max. Endpunkt ist. Würde der Startpunkt in i_Max liegen, dann hast du automatisch ein Ergebnis, d.h. wenn du kein Ergebnis bekommst, dann ist der Startpunkt von i_Q kleiner als der Startpunkt von i_Max:

 irgendwo hier liegt Startpunkt von i_Q
0 [-----------------------------------] x-1

Jetzt ist wichtig, dass der Baum nach den Startpunkten sortiert ist, also sind im linken Teilbaum die kleineren Startpunkte und im rechten die größeren. Daraus folgt, dass der kleinste Startpunkt im rechten Teilbaum mind. so groß sein muss wie der Startpunkt von i_Max. Würde i_Q jetzt also irgendein Intervall im rechten Teilbaum schneiden, müsste es mind. diesen Punkt erreichen und würde somit auch i_Max schneiden. Daraus folgt, dass wir im rechten Teilbaum kein Ergebnis haben können, falls wir links auch keins gefunden haben.

**Comment by BenSchumacher-HU** [comment]
Alles klar. Danke für die Erklärung!

**Comment by Zarok123** [comment]
Bitte noch hinzufügen, wie ihr RefSeq behandelt (Seite 25, bei buildIndex() ) - Nach Absprache mit Integration, wurde mir der Stand übermittelt, dass ihr euch um RefSeq kümmert.

**Comment by Martin-Bauer** [comment]
Das taucht später im QueryReceiver auf

**Comment by Zarok123** [comment]
Ok. Super - Kann ich hinzufügen: "Die RefSeq-Daten werden hierbei von der Middleware aufbereitet." oder irgendwas, damit herausgeht, dass ich euch komplett drum kümmert? Oder fällt dir eine bessere Formulierung ein?

**Comment by Martin-Bauer** [comment]
Füg das ruhig hinzu. Ich denke nicht, dass mir was besseres einfällt.

**Comment by Zarok123** [comment]
Bitte den Punkt noch für 4.7 abarbeiten. Oben wurde aktualisiert:

* **Bitte fügt für 4.7. noch Tests für nur teilweise Überschneidung hinzu.**
```
Testvorbereitung: addGene (TestGen, 350,500)
Tests:
search( 300,600) -> Ergebnis "TestGene"
search( 380,600) -> Ergebnis "TestGene" (oder leer, je nach Antwort auf die erste Frage oben)
search( 100, 200) -> Ergebnis leer

````

Sonst ist soweit alles fertig.

**Comment by Martin-Bauer** [comment]
Das wird garnicht nötig sein, da in der Datenstruktur letztendlich nur nach den Gennamen gesucht werden kann. nach Intervallen soll im GeneTranslator nicht gesucht werden

**Comment by Zarok123** [comment]
Stimmt. Ist keine Funktion vom GenTranslator.

Dann passt das soweit. Danke!

**Comment by Zarok123** [comment]
Bitte JSON im Bezug auf subintervall anpassen. Wurde aus der aktuellen JSON-Version entfernt.
Die neue Version findet sich unter dem Branch fix/JSON

**Comment by Zarok123** [comment]
Done! Closed.
