### ISSUE TITLE
Prezifikation des Frontends korrigieren

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen#7]
Ein paar Sachen müssen noch behoben und geklärt werden:
* ~~Bei den Abbildungen 12 und 13 fehlen die Möglichkeiten Filter vorzunehmen~~
* ~~Als Hinweis: "Position" ist als Begriff recht missverständlich. Wollt ihr nicht lieber "Intervall" verwenden?~~
* ~~In Abbildung 16 sollte statt fetchData() die entsprechenden JSON Nachrichten stehen.~~
* ~~Der Satz "Wie für dynamische Sprachen üblich, werden alle Öffentlichen JavaScript-Funktionen
mit Unit-Tests abgedeckt." ist ein wenig merkwürdig. Auch in nicht dynamischen Sprachen werden die öffentlichen Funktionen doch getestet. oder?~~
* ~~Zu 6.6: Die Tests sollten noch genauer geschrieben werden. Dies erleichtert später das automatische Testen. Z.B. bei 6.6.2: Wird eine Quelle oder alle alle Quellen getestet? Wenn eine, welche dann? Oder bei 6.6.1.3: Was ist das Intervall nach dem gesucht wird? Welche ist das Gen für 6.6.1.4? Dazu kann einfach per definierten JSON Nachrichten von der Middleware angenommen werden, wenn  keine "echten" Daten verwendet werden sollen.~~
* ~~Nur als Nachfrage: Werden alle Tests automatisiert?~~

Edit: Für die Änderungen gibt es den Branch fix/frontend_spec

**Comment by kasperkopf** [comment]
Aktueller Stand des Fix im Pull request.

**Comment by Zarok123** [comment]
Fertig! Closed.
